### ISSUE TITLE
error when event has no image

### ISSUE THREAD

**Issue by allilengyi** [tracking-exposed/librevent#2]
if FB event has no image https://github.com/tracking-exposed/librevent/blob/main/automation/src/guardoni.js#L38 leads to the error
`Error in page operations Evaluation failed: TypeError: Cannot read property 'getAttribute' of null`

**Comment by vecna** [comment]
Thanks, fixed and tested this way:

```
DEBUG=*,-puppeteer*,-follow-redirects  node src/guardoni.js --page https://www.facebook.com/LCIResearch/events/ --profile newer
DEBUG=*,-puppeteer*,-follow-redirects node src/guardoni.js  --pointer  pointers/2021-08-25+09-48+events-page+LCIResearch.json --profile newer
```

I left this comment as suggestion/memorandum:

*we should build from a page of our a variety of different events and test if the are correctly acquired.*
